### ISSUE TITLE
Livesite lacks excerpts on front-page blog posts

### ISSUE THREAD

**Issue by WorldsEndless** [BYU-ODH/wp-humanities-byu#467]
Staging has excerpts. Where are the live ones? 

This is probably a branch issue -- master doesn't have the latest code that uses that

**Comment by WorldsEndless** [comment]
It appears that it is a deeper problem than `the_excerpt` because `the_content` is not working either

**Comment by kwoods8** [comment]
After a systematic check, this doesn't appear to be a plugin conflict.

**Comment by WorldsEndless** [comment]
Let's start digging through the code to find out what function is actually failing, starting in get_the_content

https://developer.wordpress.org/reference/functions/get_the_content/

**Comment by kwoods8** [comment]
I was able to get the text to display. Now, I'll just need to write a function that automatically does this and truncates it properly.

**Comment by kwoods8** [comment]
Currently, this code only pulls content from the `Default Content`. If there's nothing in there (ie. if the text is ONLY in Elementor), this won't display anything. I'll need to make an if statement of some kind for it to work.

**Comment by kwoods8** [comment]
Excerpts for pages in Elementor and for pages in Default Content now display; however, if an article has both Elementor content and Default Content, excerpts for both display. Example: 
![image](https://user-images.githubusercontent.com/80128034/181546228-9cde6158-d089-491b-a3ad-1ed0fca84b12.png)

I currently have an if/else statement set up for this, but something about it apparently isn't working.

**Comment by spencercheng** [comment]
Once flexible.content is removed, the `the_excerpt()` is being called

**Comment by WorldsEndless** [comment]
Now that we are no longer hiding the WordPress Content field, the_excerpt works as expected whether or not Elementor is used.
