### ISSUE TITLE
Get rid of "Content Views" plugin, customize our own /blogs page

### ISSUE THREAD

**Issue by WorldsEndless** [BYU-ODH/wp-humanities-byu#473]
At some point a plugin was added to implement the view at https://odh.byu.edu/blog/

We should definitely be able to make this page with what we have, probably even out of the box. Let's get the /blog listing working without the extra plugin  (which is only used on this one page)

This is from #455

**Comment by WorldsEndless** [comment]
@spencercheng  please guide @julianayue in working on this issue

**Comment by spencercheng** [comment]
The image and all the text including the excerpt are now showing. We are working on making it not overlap.
![image](https://user-images.githubusercontent.com/89827794/173402049-9775a634-4c4c-455e-9ac6-0da8ae96d7bb.png)

**Comment by spencercheng** [comment]
@WorldsEndless The conflict has been resolved. Do we want to wait until the excerpt issue has been fixed to pull it?
