### ISSUE TITLE
Updates for Project pages

### ISSUE THREAD

**Issue by briancroxall** [BYU-ODH/wp-humanities-byu#474]
- [x] A field should be created for `Project Director(s)`. In some ways, this could be the `non-ODH Collaborators` field that has been retitled to give individuals more credit for what they bring to the table.
- [x] The `Project Director(s)` field should be multi-select
- [x] Non-ODH Collaborators should be multi-select (unless it's renamed as Project Directors)

**Comment by briancroxall** [comment]
@WorldsEndless: This is a good question, and one that I'm not sure how to solve. I think it's critical that someone like Jill or Dana be recognized as "Directors" rather than just "Non-ODH personnel." That could lead to hurt feelings, which wouldn't be useful for our office.

**Comment by WorldsEndless** [comment]
Okay -- let's make this refer to our personnel list again. In the event the Project Director is an ODH person, let's just add them to the personnel list with their directory link as their "url"

**Comment by kwoods8** [comment]
New multi-select field of `Project Director(s)` that draws from `Collaborators` Pod.
