### ISSUE TITLE
Truncation on projects page needs updating

### ISSUE THREAD

**Issue by briancroxall** [BYU-ODH/wp-humanities-byu#475]
The [projects page](https://odh.byu.edu/projects/) needs to truncate the text on projects more consistently. At the moment, the boxes are of widely different heights.
![2022-06-07_12-53-44](https://user-images.githubusercontent.com/1005115/172460472-f4ab2c7b-4963-4dfd-9b12-a09d6833b814.png)
![2022-06-07_12-53-53](https://user-images.githubusercontent.com/1005115/172460489-1d38d2f0-c2dc-47a3-8265-ed4df5ca9956.png)

The text attempts to truncate (see the ellipses in the image below) but then continues on as if it hadn't been.
![2022-06-07_12-53-44](https://user-images.githubusercontent.com/1005115/172460780-32d6170e-dfc1-423e-ac2c-da3c9b4471eb.png)

**Comment by spencercheng** [comment]
Pods template in Production has been updatedc
