### ISSUE TITLE
Add sensible default images (header, etc)

### ISSUE THREAD

**Issue by WorldsEndless** [BYU-ODH/wp-humanities-byu#487]
When no files are present, images should still display right.

Default header image as a BYU one should work nicely.

**Comment by WorldsEndless** [comment]
good options at https://photo.byu.edu/

**Comment by YuiZoldyck** [comment]
@WorldsEndless Other than the images for the header, where are the other images used? And do we add the images found onto the resource folder?

**Comment by YuiZoldyck** [comment]
Removed grayscale and blue overlay over the header. 
<img width="1440" alt="Screen Shot 2022-08-04 at 6 15 22 PM" src="https://user-images.githubusercontent.com/89797588/182976145-817544c3-0024-4b19-8a92-c7d6ea0efa41.png">

**Comment by YuiZoldyck** [comment]
<img width="1440" alt="Screen Shot 2022-08-05 at 2 10 43 PM" src="https://user-images.githubusercontent.com/89797588/183155594-69e7fafb-09a4-41f5-8747-f92e832281c8.png">

<img width="1440" alt="Screen Shot 2022-08-05 at 2 10 32 PM" src="https://user-images.githubusercontent.com/89797588/183155633-4c5e2130-d002-4e72-93a5-960b748a2d31.png">

what theme looks like on posts and pages on raw installation of theme
