### ISSUE TITLE
search issues: results don't come as expected

### ISSUE THREAD

**Issue by WorldsEndless** [BYU-ODH/wp-humanities-byu#489]
some pages don't show up -- https://odh.byu.edu/?s=Tory or https://odh.byu.edu/?s=Devin

However, 

https://odh.byu.edu/?s=russell

has all sorts of results, including the directory page. 

How do we get all the results to show up properly? Does WordPress just need to do some kind of reindexing?

**Comment by kwoods8** [comment]
At least part of the issue here appears to be the Relevanssi plugin, which we had installed to improve the search on the projects page. When I deactivate it, https://humstaging.byu.edu/odh/?s=tory returns results, but https://humstaging.byu.edu/odh/?s=russell returns fewer results than before.

**Comment by WorldsEndless** [comment]
Also, we found that we are getting different results for different computers, eg https://humstaging.byu.edu/odh/?s=bonnie

**Comment by WorldsEndless** [comment]
Different results seem to involve whether you are logged in or not

**Comment by WorldsEndless** [comment]
This is definitely related to Relevanssi, which we don't want to get rid of because it is needed for facet searching on the project page. https://www.relevanssi.com/category/knowledge-base/

**Comment by kwoods8** [comment]
Relevanssi's [debugging methods](https://www.relevanssi.com/knowledge-base/debugging-relevanssi-searching-issues/) recommend trying an admin search on the dashboard to see if it produces the results we want. It does on staging, so it appears there might be interference from our theme, but I'll need to look into it more.

**Comment by WorldsEndless** [comment]
Let's try changing themes and verify that the theme is the problem

**Comment by kwoods8** [comment]
On the 2021 theme, 'tory' also returned no results. Though there were a couple errors as well.
![image](https://user-images.githubusercontent.com/80128034/182401247-f74abfe2-12b9-42e8-8b0e-bd4594b68bd9.png)

I'll go to the Relevanssi forum and explain what I've done so far and see what they've got to say.

**Comment by kwoods8** [comment]
Important links for this issue:

[Read before asking questions on the forum](https://wordpress.org/support/topic/read-this-before-asking-questions/) (from the plugin author)
[Debugging methods for Relevanssi](https://www.relevanssi.com/knowledge-base/debugging-relevanssi-searching-issues/) - I did the admin search and tested the theme; however, there are several more things that should be tried before posting on the forum
[Relevanssi Knowledge Base](https://www.relevanssi.com/category/knowledge-base/) - This can help with diagnosing the problem as well as finding a solution.

**Comment by WorldsEndless** [comment]
Now working on staging, but not yet on prod. Why?

https://odh.byu.edu/?s=Tory
https://humstaging.byu.edu/odh/?s=Tory

**Comment by WorldsEndless** [comment]
Maybe a different plugin would give the features without breaking things? Julianna recommended Ivory Search. Let's try it.

**Comment by WorldsEndless** [comment]
we reindexed and now Tory is working but Devin is still (good on staging, absent on prod)

**Comment by WorldsEndless** [comment]
https://thomasgriffin.com/how-to-include-custom-post-types-in-wordpress-search-results/
