### ISSUE TITLE
Directory results don't show up with details on search 

### ISSUE THREAD

**Issue by WorldsEndless** [BYU-ODH/wp-humanities-byu#490]
like https://odh.byu.edu/?s=russell . His diretory page is linked, but without any of the details that are meant to be included like at https://odh.byu.edu/people/?search=russel

The same is true of projects.

**Comment by spencercheng** [comment]
Seems like searchform.php and search.php could be the cause of this

**Comment by WorldsEndless** [comment]
https://developer.wordpress.org/reference/functions/get_post_type/

**Comment by spencercheng** [comment]
https://docs.pods.io/code/pods/

**Comment by spencercheng** [comment]
After my meeting with @kwoods8  today, we both thought it would be a better Idea that all the Post types look stylistically similar, otherwise it would be very uncanny having multiple styles in one page. For example, if we were to put tory in the search field, it would return more than one post types including persons, blogs, pages etc. To render those like how they are originally I think would defeat the purpose of a search page. 

I know that I missed alot of details that we discussed. @kwoods8  please feel free to chime in!

**Comment by WorldsEndless** [comment]
Excellent points about the UI cohesion. However, the ultimate in uniformity is the google search on just this site -- but we can do better than that. We should include extra information available to shorten the search process: when the result is a directory page, show their email and phone; when a project, share the project owner and maybe some of the text.

To avoid style clash, I recommend using a vertical layout with a clear division between each result, so there is no "side-by-side" comparison overload happening.

**Comment by spencercheng** [comment]
Search Description for Persons : 
![image](https://user-images.githubusercontent.com/89827794/183456672-6c7ce64d-e269-43ee-95c3-28493d068313.png)

Search Description for Projects:
![image](https://user-images.githubusercontent.com/89827794/183456822-42a4d8b7-e5bb-4f91-a03b-d87c6306c7e2.png)

**Comment by spencercheng** [comment]
- Needs Icon for persons description
- Specialty (if not straightforward)
- Center Images

**Comment by spencercheng** [comment]
![image](https://user-images.githubusercontent.com/89827794/183732718-c8fa1912-2a81-42bc-9c8e-80e3189ee058.png)

**Comment by spencercheng** [comment]
Would we want an icon for the Name as well? @WorldsEndless

**Comment by WorldsEndless** [comment]
No, no icon for name. Mostly exactly what you see in the example above.

**Comment by spencercheng** [comment]
Okay! Sounds good.

**Comment by spencercheng** [comment]
![image](https://user-images.githubusercontent.com/89827794/184404088-d66e4320-a011-46d4-a1b5-f11d9dee0056.png)
Images centered. 
Icons and Research Areas Show.

**Comment by spencercheng** [comment]
![image](https://user-images.githubusercontent.com/89827794/184404224-693a307b-b3e6-4da6-8470-df9272daab16.png)
Projects - Project Owner Show 
Images Centered 
Excerpts Show.
