### ISSUE TITLE
"projects" should be line-separated on individual profile page

### ISSUE THREAD

**Issue by WorldsEndless** [BYU-ODH/wp-humanities-byu#491]
styling issue. On mobile, it is hard to distinguish projects categories from each other, such as "active". Perhaps a line separation. 

![image](https://user-images.githubusercontent.com/5042778/178547008-d36a2921-dd66-4527-9303-7a901a269953.png)

above is mobile view of https://odh.byu.edu/person/tory-anderson/

**Comment by WorldsEndless** [comment]
Also, the category titles should not be smaller than their contents

**Comment by kwoods8** [comment]
![image](https://user-images.githubusercontent.com/80128034/179018446-490c71bc-3625-4c0f-bc96-dc4ba76a7b78.png)

Changed the headings to make them a little more distinct.

**Comment by kwoods8** [comment]
![image](https://user-images.githubusercontent.com/80128034/179023981-63406e98-1d5f-409f-96fb-65b0dcf84c82.png)

I don't think a line separation looks great, especially because it's a style we don't use anywhere else on the page.

**Comment by kwoods8** [comment]
![image](https://user-images.githubusercontent.com/80128034/179809674-7805a4b7-4b12-4bb7-9f48-3b71dcbdca1b.png)

What if we had some white space between the categories?

**Comment by WorldsEndless** [comment]
More white space is probably the right answer, although I like the separating lines. But go with the whitespace as long as it's responsive for different screen sizes; this is probably a more "correct" solution from a design perspective.

**Comment by WorldsEndless** [comment]
The latter. It should be equally functional and equally pleasant across sizes
