### ISSUE TITLE
Search page has a redundant search bar

### ISSUE THREAD

**Issue by WorldsEndless** [BYU-ODH/wp-humanities-byu#492]
When you go to the search page there is another search bar.

![image](https://user-images.githubusercontent.com/5042778/178548724-bcb90b12-f382-4ba9-b2e2-052c2e3699f4.png)

That's https://odh.byu.edu/?s=a

**Comment by YuiZoldyck** [comment]
Took out the redundant search bar code from php

<img width="788" alt="Screen Shot 2022-07-12 at 2 18 16 PM" src="https://user-images.githubusercontent.com/89797588/178587309-48354a63-e5fc-4b12-b251-41508e9d3699.png">

![Screen Shot 2022-07-12 at 14 18 19 (2)](https://user-images.githubusercontent.com/89797588/178587719-b9735c65-b8b5-45e1-b84f-684edf485186.jpeg)

**Comment by YuiZoldyck** [comment]
Still have redundant search bar on searches with content. Search.php

**Comment by YuiZoldyck** [comment]
![Screen Shot 2022-07-26 at 4 48 43 PM](https://user-images.githubusercontent.com/89797588/181125380-8b5b8a47-6cc3-4234-80f7-429cd64a7191.png)
<img width="1210" alt="Screen Shot 2022-07-26 at 10 05 24 AM" src="https://user-images.githubusercontent.com/89797588/181125385-dca484c2-0aa2-49e7-b173-6f77c64c2e9a.png">
redundant search bar on page with search results fixed
