### ISSUE TITLE
Project page: make "project status" buttons clickable

### ISSUE THREAD

**Issue by WorldsEndless** [BYU-ODH/wp-humanities-byu#498]
Clicking any of the three status buttons at the top should be clickable to result in filtering to the projects that have that status. 

![image](https://user-images.githubusercontent.com/5042778/182242653-99728c60-bfd3-4ad5-b46f-e9966a0d3385.png)

**Comment by YuiZoldyck** [comment]
Here is how it looks after I took out the original Facet buttons that were put in place. The entire thing including the checkbox itself is clickable. Not sure if we want to make it the exact same as it looked before. 
<img width="1440" alt="Screen Shot 2022-08-24 at 8 19 13 AM" src="https://user-images.githubusercontent.com/89797588/186442754-d636363a-f73d-4623-bbdc-db6687d44021.png">

<img width="1440" alt="Screen Shot 2022-08-24 at 8 19 19 AM" src="https://user-images.githubusercontent.com/89797588/186442714-0ae0a26e-990f-46a2-acfe-308e3b88aa72.png">

**Comment by YuiZoldyck** [comment]
@WorldsEndless  Here are some more further changes I added to the styling of the buttons. I am still working to see if it is possible to transfer the border colors from before, but that will have to be whenever the fix on the project borders happen. 
<img width="1440" alt="Screen Shot 2022-08-31 at 8 39 59 PM" src="https://user-images.githubusercontent.com/89797588/187820694-74cea657-6b5e-4081-a187-371e6ffdf1f7.png">
<img width="1440" alt="Screen Shot 2022-08-31 at 8 39 52 PM" src="https://user-images.githubusercontent.com/89797588/187820696-faacd350-1530-4fe6-92d8-d28b9a96a148.png">
