### ISSUE TITLE
Improve styling UI of the nav menu

### ISSUE THREAD

**Issue by WorldsEndless** [BYU-ODH/wp-humanities-byu#510]
Everything in the nav that now has "hover over" to cause underlining should also be clickable as the link. This is a minor DOM change. 

![image](https://user-images.githubusercontent.com/5042778/183702779-fc7628f7-fa45-4c9f-b7bd-fb589e51d2c3.png)

**Comment by spencercheng** [comment]
Which file should I be looking to edit the nav bar? All I'm seeing is the function `wp_nav_menu()`

**Comment by WorldsEndless** [comment]
This can be improved by changing the padding on the nav items to margin, instead. However, the units also need to be changed for responsiveness. Not PX but something responsive live REM.

**Comment by spencercheng** [comment]
This is what the nav bar looks like after changing the unites to REM and from Padding to Margin. 
![image](https://user-images.githubusercontent.com/89827794/183759575-b64f82d8-fd35-40bb-acd8-a69938f4b7a0.png)
Compare with the Original: 
![Uploading image.png…]()

**Comment by spencercheng** [comment]
You can't really see a difference from the images uploaded, but the top and bottom margin are bigger than the original nav bar even using 1REM. What are your thoughts on using 1vh/vw? @WorldsEndless

**Comment by spencercheng** [comment]
@WorldsEndless These changes I believe have been pushed up on Branch styleFixing521.  We should probably fix this asap.

**Comment by spencercheng** [comment]
I've made the margin-top and bottom to be 1vh because 1rem is bigger than the original nav bar.
