### ISSUE TITLE
Remove Septera from the dashboard

### ISSUE THREAD

**Issue by WorldsEndless** [BYU-ODH/wp-humanities-byu#513]
These should be removed somehow:

![image](https://user-images.githubusercontent.com/5042778/183765800-e6f6dc0e-77d7-4d25-8dcd-3279807a36cb.png)

**Comment by spencercheng** [comment]
https://wpmudev.com/blog/how-to-remove-menus-from-the-wordpress-dashboard/

**Comment by spencercheng** [comment]
There is a plugin called Menu Editor that does a great job with this. the downside is It hides the menu options, but doesn't delete them.

**Comment by spencercheng** [comment]
https://developer.wordpress.org/reference/classes/wp_admin_bar/remove_node/

**Comment by spencercheng** [comment]
https://developer.wordpress.org/reference/functions/remove_submenu_page/

**Comment by WorldsEndless** [comment]
related to #514 and #528, which might take care of this issue without further work

**Comment by WorldsEndless** [comment]
Because we might actually end up simply switching from Septera, this might take care of itself.
