### ISSUE TITLE
Remove all things septera from the code

### ISSUE THREAD

**Issue by WorldsEndless** [BYU-ODH/wp-humanities-byu#514]
Find out which things we actually use from Septera -- there might not be very many -- and see what we can easily remove.

**Comment by WorldsEndless** [comment]
This also goes for things marked "cryout", which is Septera's parent company

**Comment by julianayue** [comment]
Cryout/septera code that will cause issues when removed:

**Comment by WorldsEndless** [comment]
Find ways in native WordPress to replace these things. For example, https://developer.wordpress.org/reference/functions/get_header/ get_header was found by examining how it is done with https://github.com/WordPress/twentysixteen

**Comment by WorldsEndless** [comment]
front-page.php needs attention. We want things to stay looking as they do now, but with Septera removed from front-page.php. This will take some care.

**Comment by WorldsEndless** [comment]
Based on #528 we've tried just removing a bunch of the files, but the breaks are so interwoven that this is not a viable way forward. We are going to need to more carefully remove things piece by piece, with an issue per big removal.

**Comment by julianayue** [comment]
1. Try using WP 2020 theme.
2. Make child theme
3. Try changing it to look like odh template
4. Is it easier to have our own theme? (optional)
