### ISSUE TITLE
Upgrade WordPress to 6

### ISSUE THREAD

**Issue by WorldsEndless** [BYU-ODH/wp-humanities-byu#527]
This needs to be done on Dev, and then on prod if all is good. It is a major version change, so there are good chances it will break stuff

**Comment by WorldsEndless** [comment]
https://humstaging.byu.edu/odh/wp-admin/update-core.php

**Comment by WorldsEndless** [comment]
Worked for Spencer

**Comment by spencercheng** [comment]
Works on Humstaging as well.

**Comment by spencercheng** [comment]
@WorldsEndless  Wordpress 6 has been updated on humstaging as well. Is this issue good to be closed? On the otherhand, it still doesn't explain why the default content came back on the humstaging and not on localhost

**Comment by WorldsEndless** [comment]
@nuevenueve Can you please take care of this on prod? It should be all in order and ready to go

**Comment by nuevenueve** [comment]
I am not quite sure what is needed on this issue. 
What is the issue for this issue? Thanks.

**Comment by WorldsEndless** [comment]
We have double checked on both staging and on the local sites that upgrading WordPress to the latest version (6.something) should be fine without any plugins breaking. Please upgrade the production [odh.byu.edu](http://odh.byu.edu/) site to the latest WordPress (according to the "Update available" message on the admin dashboard).
