### ISSUE TITLE
Remove Septera/cryout files

### ISSUE THREAD

**Issue by WorldsEndless** [BYU-ODH/wp-humanities-byu#528]
Things like the Septera/cryout files directories should be removed, but this will take some careful work. Related to #514

**Comment by YuiZoldyck** [comment]
@WorldsEndless I just wanted to double check but it is simply the folder under wp-humanities-byu that is called cryout that we want to remove for this issue? Or is there anything else that should be removed as well?

**Comment by WorldsEndless** [comment]
Double check that the admin and customize pages are still functioning; that is where Septera might most be used.

**Comment by WorldsEndless** [comment]
This will need #514 first

**Comment by WorldsEndless** [comment]
Now that there is a list from @julianayue on #514 we have a good aim on the things that will cause trouble here
