### ISSUE TITLE
unhide "default content" in the CSS

### ISSUE THREAD

**Issue by WorldsEndless** [BYU-ODH/wp-humanities-byu#529]

**Comment by spencercheng** [comment]
Humstaging seems to have the normal editor but my localhost doesn't

**Comment by spencercheng** [comment]
Flexible content, uncheck Content Editor

**Comment by spencercheng** [comment]
Waiting to make sure all the code + content is moved over right?

**Comment by WorldsEndless** [comment]
No, we need to unhide the default content in order for them to move that content.

**Comment by spencercheng** [comment]
![image](https://user-images.githubusercontent.com/89827794/190704176-b2572e79-2d4b-42e4-a047-62b541d58b67.png)
It is content editor shows.

**Comment by WorldsEndless** [comment]
We need this to be unhidden on the "Person" type as well

**Comment by WorldsEndless** [comment]
on Person it is hidden in the definition of the People https://github.com/BYU-ODH/wp-humanities-byu/blob/f09dc71cedc0adc675a04d20942476e1d84264c7/functions.php#L186

Add "editor", as per https://developer.wordpress.org/reference/functions/register_post_type/

**Comment by WorldsEndless** [comment]
postdivrich is hiding the content, and ACF is using postdivrich. Why is postdivrich being hidden? Is there an ACF setting somewhere? Note that it is NOT checked as disabled on the ACF Person Details page.

**Comment by WorldsEndless** [comment]
fixed on dev by adding editor to the field supports
