### ISSUE TITLE
Remove flexible-content.php

### ISSUE THREAD

**Issue by WorldsEndless** [BYU-ODH/wp-humanities-byu#531]

**Comment by spencercheng** [comment]
Check Front-page and blogs to see if anything is broken if deleted.

**Comment by WorldsEndless** [comment]
This needs to wait for #532 so that no content is lost

**Comment by WorldsEndless** [comment]
#532 is finished now, so we are ready to push the code changes

**Comment by spencercheng** [comment]
Sounds good!

**Comment by spencercheng** [comment]
I have removed `flexible-content.php` from my localhost, there doesn't seem to be anything that is broken in the front page/blogs:

![image](https://user-images.githubusercontent.com/89827794/192004296-1075f584-576b-4415-9f3c-369a13d23851.png)

**Comment by spencercheng** [comment]
On the other hand, peoples page does not seem to show up at all. 
![image](https://user-images.githubusercontent.com/89827794/192005786-f80d6d5d-655e-4033-8b3e-fbb180621b05.png)

**Comment by WorldsEndless** [comment]
We found in our meeting that the reason it fails is because the people page was using the flexible content default for its shortcode. Fixed!
