### ISSUE TITLE
(@nuevenueve  team on Prod) Copy stuff added to "flexible content" fields to regular wordpress "default content"

### ISSUE THREAD

**Issue by WorldsEndless** [BYU-ODH/wp-humanities-byu#532]

**Comment by WorldsEndless** [comment]
@nuevenueve I believe this is ready for your team to start copying things out of the flexible content "default" areas into the built-in ones

**Comment by nuevenueve** [comment]
Okay, we have copied the posts content to the built-in editor and removed the default editor from each post. 
Let us know if you still see any issues.

**Comment by WorldsEndless** [comment]
Thanks!

**Comment by WorldsEndless** [comment]
@nuevenueve I just found out that People have default content as well. My own Person record is using it. Did you team also copy this out of the ACF default content field to a WordPress one? (it looks like the WP one might not even be visible yet)

**Comment by nuevenueve** [comment]
I did notice that there are some contents in the default content. However, the default content information is never published to your profile. You can add some extra content to the default content and will see that no thing will go to your profile. 
I think that the content on default content is never being used. :)

**Comment by WorldsEndless** [comment]
Thanks for looking in to that! Possibly it should be used, though, so we are working on #503 to make sure the same fixes are present on People as on the other post types

**Comment by nuevenueve** [comment]
I think that People section is a little bit different since it is custom-built.  
However, please let me know once developers finish people section. :)

**Comment by WorldsEndless** [comment]
We got the regular content back on the people section today, so this is good for you to double check.

**Comment by WorldsEndless** [comment]
Are we done with this, @nuevenueve ? I think we are about ready to by finished

**Comment by nuevenueve** [comment]
I believe that we have finished this task. :)

**Comment by WorldsEndless** [comment]
Thanks!
