### ISSUE TITLE
PODS mastery contents

### ISSUE THREAD

**Issue by WorldsEndless** [BYU-ODH/wp-humanities-byu#535]
What topics are must have with PODS for our usage? Think chapter titles. Some good examples:

- [x] - Shortcodes
- [x] - Exporting and importing
- [x] - Working with Facet
- [x] -  PODS templates & template export (and maybe import)

**Comment by julianayue** [comment]
- Custom Taxonomies
- FacetWP
- Elementor
- Pods template
- Creating new pods
- Adding to existing pods (taxonomies)
- Connecting pods (creating relationship)
- Short codes
- Template / Theme
- Export / import a theme

**Comment by julianayue** [comment]
Making videos (youtube private) / taking screen shots

**Comment by WorldsEndless** [comment]
@YuiZoldyck has made good initial progress at adding this the the KB

**Comment by YuiZoldyck** [comment]
https://humwebkb.byu.edu/index.php/2023/03/16/pods-mastery/

**Comment by WorldsEndless** [comment]
Change the text from e.g. "here's a link" to more descriptive "here are instructions" or "here is a video showing how to..."

**Comment by YuiZoldyck** [comment]
<img width="1440" alt="Screen Shot 2023-03-30 at 8 03 22 AM" src="https://user-images.githubusercontent.com/89797588/228861496-f119d9f6-3da7-4682-9111-9e9b0d7a2b9d.png">
<img width="1440" alt="Screen Shot 2023-03-30 at 8 03 41 AM" src="https://user-images.githubusercontent.com/89797588/228861600-5a68fcb3-4e35-4625-b1ea-5e7d9b5b2237.png">
<img width="1440" alt="Screen Shot 2023-03-30 at 8 03 31 AM" src="https://user-images.githubusercontent.com/89797588/228861671-b020ee89-691a-4b32-a15e-3fbeb3af38b8.png">
