### ISSUE TITLE
Staging "Projects" are messed up

### ISSUE THREAD

**Issue by WorldsEndless** [BYU-ODH/wp-humanities-byu#537]
https://humstaging.byu.edu/odh/projects/

on Staging the style is messed up, and for some reason only 2 are showing (although there are more in the system

![image](https://user-images.githubusercontent.com/5042778/192063495-ffe314b3-db73-498a-a5b3-975279c6cd49.png)

**Comment by spencercheng** [comment]
My localhost seems to not have this issue. 
![image](https://user-images.githubusercontent.com/89827794/193305050-f9009d54-23fc-4c27-85f2-8a6202b2122f.png)

**Comment by WorldsEndless** [comment]
This is still good on Prod, but we've tried matching the pods templates and it hasn't completely solved the problem.

**Comment by YuiZoldyck** [comment]
I went through and updated all projects so the project status is on there. Then I went into facets to add the project status checkbox. Then I went to the projects page Elementor and added in the short code for project_status.
