### ISSUE TITLE
Prod "projects" are missing data

### ISSUE THREAD

**Issue by WorldsEndless** [BYU-ODH/wp-humanities-byu#538]
Somehow all data for certain projects has been lost. Probably we can get that data back from staging (even though it has its own problems), and it is also still present on the local versions. 

Were we hacked? Or did someone delete by accident?

![image](https://user-images.githubusercontent.com/5042778/192063803-e6bdc703-3c67-42b0-9619-4c959dc4bfaf.png)

**Comment by nuevenueve** [comment]
I have restored most of contents back to project pages except for More Than Mouses and Online Interactive Hebrew Bible project pages. We don't have those two project pages on humstaging.

**Comment by WorldsEndless** [comment]
Thanks! Any idea what happened there? Was it a mistake, or a bad plugin?
