### ISSUE TITLE
Bring back "projects" on individual person pages

### ISSUE THREAD

**Issue by WorldsEndless** [BYU-ODH/wp-humanities-byu#542]
They are now missing, but were added in #333 . They need to be restored.

**Comment by WorldsEndless** [comment]
Before closing this, let's fix the String comparisons: the trouble was that now the status are capitalized and don't have the  "Status" in them. Let's variabalize these so that they are literally the same everywhere, including in the status generation

**Comment by WorldsEndless** [comment]
Make the variables in the same place as the project Status validation code, and name the variables something distinct like "odhLiveStatus"

**Comment by spencercheng** [comment]
@WorldsEndless I've just pushed the changes. Let me know what else I need to change
