### ISSUE TITLE
Links on individual project pages turn white on hover, which makes readability difficult

### ISSUE THREAD

**Issue by briancroxall** [BYU-ODH/wp-humanities-byu#546]
Links should get a different sort of decoration on hover.

![Screen Shot 2022-10-19 at 4 41 16 PM](https://user-images.githubusercontent.com/1005115/196818403-56830789-21c6-4c5d-97f4-4e37b8195d77.png)

**Comment by spencercheng** [comment]
![image](https://user-images.githubusercontent.com/89827794/197246940-e8dab152-7527-425e-8088-4d63111f1ea3.png)
I've made it so when you hover of it turns black instead of white. @WorldsEndless Let me know what is good color to use.

**Comment by spencercheng** [comment]
make it underline

**Comment by spencercheng** [comment]
text-decoration:underline
color: #00000

**Comment by WorldsEndless** [comment]
This should be a good fix. Screenshot please

**Comment by spencercheng** [comment]
<img width="960" alt="image" src="https://user-images.githubusercontent.com/89827794/198688477-753ba409-9d31-466a-994b-c9c5219e93fc.png">
