### ISSUE TITLE
Guide users more on project image uploads

### ISSUE THREAD

**Issue by WorldsEndless** [BYU-ODH/wp-humanities-byu#551]
Cropping is not always correct, and images can easily be the wrong dimensions. Are there plugins or common-sense helpers or text that can help?

**Comment by spencercheng** [comment]
https://wordpress.org/plugins/image-regenerate-select-crop/#description

**Comment by spencercheng** [comment]
https://www.commoninja.com/discover/wordpress/plugin/wp-image-cropper

**Comment by WorldsEndless** [comment]
we installed the php8-gd plugin which, after restart of the server, hopefully allows image edits. Then we just need the subtext messages on the image uploads suggesting that they use rectangle (up to 2:1) image dimensions.

**Comment by spencercheng** [comment]
@WorldsEndless  Has the server been restarted?

**Comment by spencercheng** [comment]
It appears to have been updated, but the cropping function seems to still be disabled.

**Comment by spencercheng** [comment]
Several things I have checked to see if they were hindering the cropping features: 
1. Updated all plugins - Hopefully to fix bugs
2. Deactivating some plugins at a time to see if they were conflicting with the cropping feature.
3. Media Settings
4. Check for custom made function


So far none of these approach seem to work

**Comment by WorldsEndless** [comment]
next would be to find a place that IS working, so we can check differences. For example, does a local install with AAMPS work?

**Comment by WorldsEndless** [comment]
Next contact: see if @nuevenueve  can help figure this out

**Comment by nuevenueve** [comment]
I will take a look at this issue.
I assume that the website is odh.byu.edu and assume that issue is that no image shows up when you click on edit image. 

![image](https://user-images.githubusercontent.com/63419009/213522362-dc55855b-ba3b-4488-995d-f15ab35c14ed.png)

**Comment by WorldsEndless** [comment]
edit image functionality is not working on humstaging, or on humanities server (prod), but it IS working on the farm at humwp.byu.edu

**Comment by WorldsEndless** [comment]
Mark and John are solving the technical side of this. But we need still to provide "recommended dimensions for ___ are..." for each of 

- [ ] blog posts
- [ ] project images
- [ ] directory profiles

Before we can do this, we need to figure out, "what are the need  dimensions?"

**Comment by nuevenueve** [comment]
Okay, I was able to resolve the issue after I installed php7.2-gd. 
It's working on sldsw, but it didn't work on odh. 
The reason is on odh's theme. If you change the current theme to another one, the feature of edit image will start to work.
After I change the theme to another one.  
![image](https://user-images.githubusercontent.com/63419009/214673331-9f2ca742-1e7c-4262-8215-1759ce90ee9e.png)

**Comment by spencercheng** [comment]
After doing some research, here is what I found:

Standard Dimensions for WordPress sites are differentiated by theme, the year of the theme, specific layout, etc. Here are the recommend Dimensions for Blog post (WordPress in General): 
- 1200 x 800 Pixels - This is for Feature Images, or Post images. The Width varies (600-800)

Septera Theme Blog Bost Dimensions:
- 800 x 600 Pixels 

For Project Images: 
We could do the size of a hero image 1920 x 1080 pixels ( Full width and the height of 600-800 pixels) 
OR We could do half of it. Probably something to discuss. @WorldsEndless 

For Directory Profiles:

250 x 250 pixels taking a square shape. (Wordpress in general)
Septera 200x200 Pixels.

**Comment by spencercheng** [comment]
Look for ways under the media section to tell professors about the recommended Dimensions.

**Comment by spencercheng** [comment]
After doing some research, I haven't been able to find anything on adding text to the media library.

**Comment by WorldsEndless** [comment]
example of how this could work with just the style.css
```css
#post-upload-info::after {
	content: "image size should be 4x3 dimensions";
	font-size: 1rem;
}
```

**Comment by spencercheng** [comment]
on the inspect element, it works perfectly fine, but when I try implementing it in the style.css, nothing seems to have changed.
