### ISSUE TITLE
On Emeritus status people, replace phone/address with "Alumnus"

### ISSUE THREAD

**Issue by WorldsEndless** [BYU-ODH/wp-humanities-byu#560]
![image](https://user-images.githubusercontent.com/5042778/199795625-89d13d0a-9275-4572-a3d3-459923bc8c0e.png)

**Comment by WorldsEndless** [comment]
Alumni will have the status "Emeritus" 

![image](https://user-images.githubusercontent.com/5042778/200069885-9f662cd9-64b1-4342-abdd-a696a4a88b5e.png)

**Comment by YuiZoldyck** [comment]
<img width="1440" alt="Screen Shot 2022-11-17 at 9 54 18 AM" src="https://user-images.githubusercontent.com/89797588/202508319-8252486d-cee2-47c4-ac24-cc2b37aa06fe.png">

<img width="1440" alt="Screen Shot 2022-11-17 at 9 54 29 AM" src="https://user-images.githubusercontent.com/89797588/202508355-71e129c7-620d-41b4-9305-34abc799b44f.png">
