### ISSUE TITLE
Search results should show more info

### ISSUE THREAD

**Issue by WorldsEndless** [BYU-ODH/wp-humanities-byu#561]
For example, when search results are matching a picture, the thumbnail of that picture should be shown.

![image](https://user-images.githubusercontent.com/5042778/200071408-f8125101-3d29-450d-b725-f4851ecf2d2b.png)

- [x] Show images of results whenever possible
- [x] Don't show content-less types, such as collaborators
- [x] Start the result text with the type of the result, such as "Person" or "Project" or "Image"

**Comment by spencercheng** [comment]
This can be done in the functions.php file. I remember I did it in another file but I think we transferred it to the functions.php file.

**Comment by spencercheng** [comment]
Currently search results without images have default humanities logo, as well as the type of result are showing, now working on styling it.

**Comment by WorldsEndless** [comment]
Actually, we should have content on issues that don't have collaborators

https://github.com/BYU-ODH/wp-humanities-byu/issues/565

**Comment by spencercheng** [comment]
What else needs to be done on this ticket - Are we good to close?

**Comment by WorldsEndless** [comment]
The same function (though different styling) may be used for both this search page and the actual collaborator page #565

**Comment by WorldsEndless** [comment]
Every item type should declare what type it is, even if an empty "default image" situation comes up

**Comment by spencercheng** [comment]
![image](https://user-images.githubusercontent.com/89827794/226383215-f8a5fb46-8fbf-421b-8ded-385bb15343e2.png)

**Comment by WorldsEndless** [comment]
closed by #570
