### ISSUE TITLE
It would be nice if the pictures on the People page could be larger

### ISSUE THREAD

**Issue by briancroxall** [BYU-ODH/wp-humanities-byu#563]
I recognize that the pictures can't be as large as the ones on the College website if we also want to have listings for our areas of expertise, but I think it could still be dialed up some.

**Comment by briancroxall** [comment]
I'm not sure if this pull request has ever been finished, but the images are still small and I think that's what's contributing to our eyes looking a bit weird.
![2023-01-25_11-36-31](https://user-images.githubusercontent.com/1005115/214653006-e7e92ed0-96e3-47d5-a3c2-210f202232d4.png)

**Comment by WorldsEndless** [comment]
The applicable styles are in the directory app, not WordPress. I will take care of this tonight.
