### ISSUE TITLE
Sub menu items do not receive nested URLs

### ISSUE THREAD

**Issue by nuevenueve** [BYU-ODH/wp-humanities-byu#566]
When Brian tried to add a sub menu item to the main menu, the added menu item couldn't show up under menu category. 

![image](https://user-images.githubusercontent.com/63419009/217374179-2df3de74-da4f-4966-8f22-d64a14ce2db4.png)

![image](https://user-images.githubusercontent.com/63419009/217374317-cde56ffb-fe65-4a27-b353-e6bcfb9a5d61.png)

**Comment by briancroxall** [comment]
I'm not terribly concerned about it not showing up in the nav bar. But, while the page had "projects" listed as its parent in the WP interface, the page would not appear at its proper URL.

**Comment by WorldsEndless** [comment]
Our theme does not support drop-down menus by design. Dropdown menus are bad design practice. See:
- https://wpjohnny.com/avoid-dropdown-hamburger-menus/
- https://www.nngroup.com/articles/drop-down-menus/
- https://neilpatel.com/blog/common-website-navigation-mistakes/

If we need a portal page for nested content, search engines and mobile are much happier with it.

But the url issue needs attention.

**Comment by WorldsEndless** [comment]
For example, in the original image above, we should see a URL like `/proposals/process`

**Comment by spencercheng** [comment]
After working on it with Tory, this is our find: 
Changing the URL under the menu is not the right way to do it, instead you can changed the URL name/parent when you click on the edit button for a specific page/post you want to change. For example 
![image](https://user-images.githubusercontent.com/89827794/223290050-78e8c9bd-e215-49b8-80a6-b8b505eafaa5.png)
For example if I want the page to be under "Contact Us" then you would click on the drop down and select contact us. 
![image](https://user-images.githubusercontent.com/89827794/223290312-f989db92-9090-4875-b061-ee7782677827.png)

*Some parent categories will cause the page to not show up, but in general, it should work perfectly.

**Comment by spencercheng** [comment]
@WorldsEndless  let me know if I missed anything else!
